services:
  IntelligentIntern\OpenAIBundle\Service\ChatCompletion\:
    resource: '../src/Service/ChatCompletion/*'
    public: true
    tags:
      - { name: 'chat_completion.strategy' }

  IntelligentIntern\OpenAIBundle\Service\Embedding\:
    resource: '../src/Service/Embedding/*'
    public: true
    tags:
      - { name: 'embedding.strategy' }

  App\Factory\ChatCompletionServiceFactory:
    arguments:
      $vaultService: '@App\Service\VaultService'
      $logServiceFactory: '@App\Factory\LogServiceFactory'
      $chatCompletionResolver: '@App\Domain\ChatCompletionResolver'

  App\Factory\EmbeddingServiceFactory:
    arguments:
      $vaultService: '@App\Service\VaultService'
      $logServiceFactory: '@App\Factory\LogServiceFactory'
      $embeddingResolver: '@App\Domain\EmbeddingResolver'
