services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  IntelligentIntern\OpenAIBundle\Service\ChatCompletion\:
    resource: '../src/Service/ChatCompletion/*'
    public: true
    tags:
      - { name: 'chat_completion.strategy' }

  IntelligentIntern\OpenAIBundle\Service\Embedding\:
    resource: '../src/Service/Embedding/*'
    public: true
    tags:
      - { name: 'embedding.strategy' }
